### ISSUE TITLE
Android UI Test fails to run

### ISSUE THREAD

**Issue by dansiegel** [Xappium/xappium.uitest#3]
# Description

When running the tests locally we get an error that we could not proxy the command to the remote server.

```bash
Error Message:
   System.AggregateException : One or more errors occurred. (A new session could not be created. Details: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up. Check https://github.com/appium/appium-espresso-driver#troubleshooting regarding advanced session startup troubleshooting. (SessionNotCreated)) (The following constructor parameters did not have matching fixture data: AppFixture fixture)
---- System.InvalidOperationException : A new session could not be created. Details: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up. Check https://github.com/appium/appium-espresso-driver#troubleshooting regarding advanced session startup troubleshooting. (SessionNotCreated)
---- The following constructor parameters did not have matching fixture data: AppFixture fixture
  Stack Trace:
  
----- Inner Stack Trace #1 (System.InvalidOperationException) -----
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Appium.AppiumDriver`1..ctor(ICommandExecutor commandExecutor, ICapabilities appiumOptions)
   at OpenQA.Selenium.Appium.AppiumDriver`1..ctor(Uri remoteAddress, ICapabilities appiumOptions, TimeSpan commandTimeout)
   at OpenQA.Selenium.Appium.AppiumDriver`1..ctor(Uri remoteAddress, ICapabilities appiumOptions)
   at OpenQA.Selenium.Appium.Android.AndroidDriver`1..ctor(Uri remoteAddress, DriverOptions driverOptions)
   at Xappium.UITest.XappiumTestEngine.SetupDriver() in /Users/dansiegel/repos/Libraries/Xappium.UITest/src/Xappium.UITest/XappiumTestEngine.cs:line 81
   at Xappium.UITest.XappiumTestEngine..ctor(UITestConfiguration config) in /Users/dansiegel/repos/Libraries/Xappium.UITest/src/Xappium.UITest/XappiumTestEngine.cs:line 29
   at Xappium.UITest.AppManager.StartApp(UITestConfiguration testConfig) in /Users/dansiegel/repos/Libraries/Xappium.UITest/src/Xappium.UITest/AppManager.cs:line 57
   at Xappium.UITest.AppManager.StartApp() in /Users/dansiegel/repos/Libraries/Xappium.UITest/src/Xappium.UITest/AppManager.cs:line 25
   at TestApp.UITests.AppFixture..ctor() in /Users/dansiegel/repos/Libraries/Xappium.UITest/sample/TestApp.UITests/AppFixture.cs:line 10
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```

**Comment by dansiegel** [comment]
closing as fixed by #14... additional work to come for CI build issues
